---
title             : "Are smarter brains more efficient? An investigation of the relationship between intelligence and the alpha parameter of the Levy-Flight Model"
shorttitle        : "Alpha and Intelligence"

author: 
  - name          : "Sven Lesche"
    affiliation   : "1"
    corresponding : yes    # Define only one corresponding author
    address       : "Kurfürsten-Anlage 57"
    email         : "sven.lesche@stud.uni-heidelberg.de"
  #   role:         # Contributorship roles (e.g., CRediT, https://casrai.org/credit/)
  #     - "Conceptualization"
  #     - "Writing - Original Draft Preparation"
  #     - "Writing - Review & Editing"
  # - name          : "Author 2"
  #   affiliation   : "2"
  #   role:
  #     - "Supervision"

affiliation:
  - id            : "1"
    institution   : "Ruprecht-Karls-University Heidelberg"
  # - id            : "2"
  #   institution   : "Konstanz Business School"
  # add a second id using this syntax

authornote: |
  Author Notes go here.

# abstract: |
#   One or two sentences providing a **basic introduction** to the field,  comprehensible to a scientist in any discipline.
#   
#   Two to three sentences of **more detailed background**, comprehensible  to scientists in related disciplines.
#   
#   One sentence clearly stating the **general problem** being addressed by  this particular study.
#   
#   One sentence summarizing the main result (with the words "**here we show**" or their equivalent).
#   
#   Two or three sentences explaining what the **main result** reveals in direct comparison to what was thought to be the case previously, or how the  main result adds to previous knowledge.
#   
#   One or two sentences to put the results into a more **general context**.
#   
#   Two or three sentences to provide a **broader perspective**, readily comprehensible to a scientist in any discipline.
#   
#   <!-- https://tinyurl.com/ybremelq -->
  
keywords          : "intelligence, drift-diffusion model, levy-flight model"
# wordcount         : "X"

# bibliography      : ["r-references.bib"] # put your ref files here

floatsintext      : yes # for pics in text
linenumbers       : no
draft             : no
mask              : no

figurelist        : no
tablelist         : no
footnotelist      : no
link-citations    : true # custom addin, makes citations link to reference section
# figsintext        : yes # custom addin

classoption       : "man"
# the settings below allow compilation of APA7 style citations/documents
header-includes:
  - |
    \makeatletter
    \renewcommand{\paragraph}{\@startsection{paragraph}{4}{\parindent}%
      {0\baselineskip \@plus 0.2ex \@minus 0.2ex}%
      {-1em}%
      {\normalfont\normalsize\bfseries\typesectitle}}
    
    \renewcommand{\subparagraph}[1]{\@startsection{subparagraph}{5}{1em}%
      {0\baselineskip \@plus 0.2ex \@minus 0.2ex}%
      {-\z@\relax}%
      {\normalfont\normalsize\bfseries\itshape\hspace{\parindent}{#1}\textit{\addperi}}{\relax}}
    \makeatother
  - | 
    \raggedbottom
  - |
    \usepackage{hhline}
  - |
    \setlength{\parskip}{0pt}

csl               : "`r system.file('rmd', 'apa7.csl', package = 'papaja')`"
documentclass     : "apa7"
output            : papaja::apa6_word
---
```{r setup, include = FALSE}
# Working directory
knitr::opts_knit$set(root.dir = rprojroot::find_rstudio_root_file())

# disallow tables breaking over pages
knitr::opts_chunk$set(ft.keepnext = TRUE,
                      ft.align = "left",
                      ft.latex.float = "float")
# Seed for random number generation
set.seed(1234)
knitr::opts_chunk$set(cache.extra = knitr::rand_seed) # this adds random seed to all chunks
knitr::opts_chunk$set(autodep = TRUE)
knitr::dep_auto()
```

<!-- Setup -->
<!-- Maybe setup R libraries here -->

<!-- Here we can incorporate child markdown-documents as the separate parts -->
# Introduction
- Intelligence and mental speed

- but what parts of mental speed? Variability aswell?

- DDM and its contribution to intelligence

- extension to levy-flight

- hypothesis about alpha and intelligence
 
- Aim of this study?

# Methods

## Data
Data originally from...
## Participants
Take the following from the original study
## Tasks

### Hick Task

### Posner Task

### Sternberg Task

## Procedure

## Analysis
### Levy-Flight Model
Params of Bayesflow here

### Structural Equation Model
General model

# Results
## Model evaluation

## Bivariate relationship

## SEM

# Discussion
Low correlations, but negative direction. Need to extend this to more difficult tasks. (Sternberg may already be a difficult task)

maybe in the ongoing variability discussion
<!-- References -->

\newpage

# References
::: {#refs custom-style="Bibliography"}
:::

